services:
  - type: web
    name: second-serving-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://natashakippur:Jazminrox11$@secondserving.zqbxiye.mongodb.net/
      - key: SECRET_KEY
        value: daverocks
